// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzfdunSKPXm8APqGZyqbLvlJNtV7v2mRU',
    appId: '1:304507237033:web:a9a43ec3053e9a2a276fb8',
    messagingSenderId: '304507237033',
    projectId: 'madnew-2a0a3',
    authDomain: 'madnew-2a0a3.firebaseapp.com',
    storageBucket: 'madnew-2a0a3.appspot.com',
    measurementId: 'G-J6B2E23NTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqusbArumpZ5uo-QhmiwdBM2eSZ_36O2Q',
    appId: '1:304507237033:android:d6eb91c483ba3c75276fb8',
    messagingSenderId: '304507237033',
    projectId: 'madnew-2a0a3',
    storageBucket: 'madnew-2a0a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALLVxvQ6MfVF2g_spxi-mW-ApnqsReXxM',
    appId: '1:304507237033:ios:7fe573f8b1ebe1c0276fb8',
    messagingSenderId: '304507237033',
    projectId: 'madnew-2a0a3',
    storageBucket: 'madnew-2a0a3.appspot.com',
    iosBundleId: 'com.example.madnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALLVxvQ6MfVF2g_spxi-mW-ApnqsReXxM',
    appId: '1:304507237033:ios:9e33f6f9cb409792276fb8',
    messagingSenderId: '304507237033',
    projectId: 'madnew-2a0a3',
    storageBucket: 'madnew-2a0a3.appspot.com',
    iosBundleId: 'com.example.madnew.RunnerTests',
  );
}
